config/routes.rb
Agilesoft2::Application.routes.draw do
  devise_for :users

  resources :comments, :only => [:create, :destroy]
  
  get "/posts/:post_id" => "blogs#show", :as => "posts"
  get "/blogs/:post_id" => "blogs#show"
  delete "/posts/delete/:post_id" => "blogs#delete_post", :as => "post_delete"
  get "/create_post" => "blogs#create_post"
  get "/posts_list" => "blogs#post_list"
  get "/edit_post/:post_id" => "blogs#edit_post", :as => "edit_post"
  post "/save_post" => "blogs#save_post"
  post "/visible/:post_id" => "blogs#visible_post", :as => "visible"
  get '/rss' => 'blogs#rss'
  get '/tags/tag_filter' => 'tags#tag_filter'

  get "/about" => "home#about"

  get "sitemap.xml" => "home#sitemap", as: "sitemap", defaults: { format: "xml" }
  get "/ping" => "home#ping"

  root :to => 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :comments
	has_and_belongs_to_many :tags
  attr_accessible :author, :content, :title, :visible, :updated_at

  validates :author, :presence => true
  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
  attr_accessible :author, :content, :deleted, :blog_id, :remote_ip, :user_agent, :referrer
  validates :author, :presence => true
  validates :content, :presence => true

  after_validation :check_spam


  private

  def check_spam
  	client = Akismet::Client.new( ENV['AKISMET_API_KEY'],
  		'http://www.agilesoft.es',
  		:app_name => 'agilesoft.es',
  		:app_version => '1.0' )

  	spam = client.comment_check(self.remote_ip,
  											self.user_agent,
  											content_type: 'comment',
  											referrer: self.referrer,
  											permalink: "http://www.agilesoft.es/posts/#{blog.id}",
  											comment_author: self.author,
  											comment_content: self.content)
  	
  	self.deleted = spam if spam
  end
end

app/models/sitemap_pinger.rb
class SitemapPinger 
  SEARCH_ENGINES = {
    google: "http://www.google.com/webmasters/tools/ping?sitemap=%s",
    bing: "http://www.bing.com/webmaster/ping.aspx?siteMap=%s"
  }

  def self.ping
    SitemapLogger.info Time.now
    SEARCH_ENGINES.each do |name, url|
      request = url % CGI.escape("http://www.agilesoft.es/sitemap.xml")  
      SitemapLogger.info "  Pinging #{name} with #{request}"

      #if Rails.env == "production"
        response = Net::HTTP.get_response(URI(request))
        SitemapLogger.info "    #{response.code}: #{response.message}"
        SitemapLogger.info "    Body: #{response.body}"
      #end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :blogs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	protect_from_forgery
	
	before_filter :authenticate_user!, :except => [:index, :show, :about, :save_comment, :rss]
	before_filter :load_oldposts_tags, :only => [:index, :show]

	def index
		@blog = Blog.includes(:tags).where(visible: true).last
		if @blog
			@comments = @blog.comments.where(:deleted => false).order("created_at ASC")
		else
			@comments = []
		end
	end

	def show
		@blog = Blog.includes(:tags).find_by_id params[:post_id]
		if @blog
			@comments = @blog.comments.where(:deleted => false).order("created_at ASC")
		else
			@comments = []
		end
		render :index
	end

	def delete_post
		if params[:post_id]
			post = Blog.find_by_id params[:post_id]
			if post
				post.visible = false
				post.save
			end
		end

		redirect_to root_path
	end

	def create_post
		@blog = Blog.new
	end

	def save_post
		if !params[:post_id].nil? and !params[:post_id].empty?
			@blog = Blog.find params[:post_id]
		else
			@blog = Blog.new
		end
		
		@blog.author = params[:author]
		@blog.title = params[:title]
		@blog.content = params[:content]
		if !params[:post_id].nil? and !params[:post_id].empty?
			@blog.visible = true
		else
			@blog.visible = false
		end
		@blog.tags.clear
		params[:tags].split(",").each do |item|
			tag = Tag.where(name: item.downcase.strip).first
			if !tag
				tag = Tag.create! name: item.downcase.strip
			end
			@blog.tags << tag
		end
		@blog.updated_at = somedate = DateTime.new(params[:blog]["updated_at(1i)"].to_i, 
                        params[:blog]["updated_at(2i)"].to_i,
                        params[:blog]["updated_at(3i)"].to_i,
                        params[:blog]["updated_at(4i)"].to_i,
                        params[:blog]["updated_at(5i)"].to_i)

		if !@blog.save
			if request.referrer.match /edit/
				render :edit_post
			elsif request.referrer.match /create/
				render :create_post
			end
		else
			if request.referrer.match /edit/
				redirect_to posts_path(:post_id => @blog.id)
			elsif request.referrer.match /create/
				redirect_to :action => :post_list
			end
		end
	end

	def edit_post
		@blog = Blog.find params[:post_id]
	end

	def post_list
		@list = Blog.order("updated_at DESC")
	end

	def visible_post
		post = Blog.find params[:post_id]
		post.record_timestamps = false
		post.visible = !post.visible
		post.save
		post.record_timestamps = true
		
		redirect_to :action => :post_list
	end

	def rss
    @posts =  Blog.where(:visible=>true).order("id desc").limit(10)
    
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  private

  def load_oldposts_tags
  	@comment = Comment.new
  	@old_posts = Blog.where(visible: true).order("created_at DESC")
  	@tags = Tag.order("name ASC")
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	protect_from_forgery
	
	def destroy
		if params[:id]
			@comment = Comment.find_by_id params[:id]
			if @comment
				@comment.deleted = true
				@comment.save
			end
		end
	end

	def create
		comment = Comment.create author: params[:comment][:author], 
										         content: params[:comment][:content], 
										         blog_id: params[:post_id], 
										         deleted: false, 
										         remote_ip: request.remote_ip, 
										         user_agent: request.user_agent, 
										         referrer: request.headers[ 'HTTP_REFERER' ]
		if comment.save
			AgilesoftMailer.comment_email(comment).deliver
			redirect_to "#{posts_path(:post_id => params[:post_id])}#comments", :notice => "Comentario guardado correctamente"
		else
			redirect_to "#{posts_path(:post_id => params[:post_id])}#form_comentario", :alert => "Error guardando comentario"
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	protect_from_forgery

	before_filter :authenticate_user!, :only => [:ping]

	
	def about
	end

	def sitemap
		@static_paths = [ about_path ]
		@posts = Blog.where(visible: true).order("created_at ASC")
		respond_to do |format|
			format.xml
		end
	end

	def ping
		SitemapPinger.ping
		redirect_to root_path
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_filter :load_olposts_tags

	def tag_filter
		if params[:tags] and !params[:tags].empty?
			tag_list = params[:tags].split(',')
			@tag_filter = Tag.where(:name => tag_list.map{|t| t.downcase})
			@blogs = @tag_filter.map{|t| t.blogs}.inject(:&)
		else
			@tag_filter = []
			@blogs = Blog.where(:visible => true).order("created_at DESC")
		end
	end

	private

	def load_olposts_tags
  	@old_posts = Blog.where(visible: true).order("created_at DESC")
  	@tags = Tag.order("name ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/blogs/create_post.html.erb
<h1>Nuevo post</h1>
<%= render 'partials/form_post' %>

app/views/blogs/delete_comment.js.erb
$("div#comment_<%= @comment.id %>").remove();

app/views/blogs/edit_post.html.erb
<h1>Editar post</h1>
<%= render 'partials/form_post' %>

app/views/blogs/index.html.erb
<% if !@blog %>
  <h1 class="message">¡No hay ningún post!</h1>
<% else %>
  <div id="main_content">
    <%= render 'partials/post', :blog => @blog %>
    <hr/>
    <%= render 'partials/comentarios', :comments => @comments %>
    <hr/>
    <div id="form_comentario">
    	<%= render 'partials/form_comentario' %>
    </div>
  </div>
  
<% end %>
  
<div class="clear"></div>

<br/>

app/views/blogs/post_list.html.erb
<h1>Listado de posts</h1>
<table>
	<tr>
		<th>Título</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
<% @list.each do |post| %>
	<tr>
		<td><%= post.title %></td>
		<td><%= link_to "Ver", posts_path(:post_id => post.id) %></td>
		<td><%= link_to "Editar", edit_post_path(:post_id => post.id) %></td>
		<td>
			<% if post.visible %>
				<%= link_to "Visible", visible_path(:post_id => post.id), :method => :post %>
			<% else %>
				<%= link_to "Invisible", visible_path(:post_id => post.id), :method => :post %>
			<% end %>
		</tr>
<% end %>
</table>

app/views/blogs/save_comment.js.erb
<% if !@comment.errors.empty? %>
	alert("Error salvando comentario");
<% else %>
	$("#comments").append('<%= escape_javascript(render("partials/comentario",:comentario => @comment))%>');
<% end %>
$("#add_comentario").hide();
$("#add_comentario input[name=content]").val("");

app/views/comments/destroy.js.erb
$("div#comment_<%= @comment.id %>").remove();

app/views/home/about.html.erb
<div class="container">
    

      <h1>Contacto</h1>
      <div class="span4 offset4">
        <div class="well">

            <ul>
              <li>Email: <%= image_tag 'mail.png' %></li>
              <li>Twitter: <%= link_to '@Armeris', 'http://twitter.com/Armeris', :target => "_blank" %></li>
              <li>LinkedIn: <%= link_to "Rubén Salinas", 'http://linkedin.com/in/rubensalinasgarcia', :target => "_blank" %></li>
              <li>Google+: <%= link_to 'HED', 'http://gplus.to/hed', :target => "_blank" %></li>
            </ul>

        </div>
      </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>AgileSoft <%= "| #{@blog.title}" if @blog %></title>
  <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Swanky+and+Moo+Moo"%>
  <script type="text/javascript" src="https://apis.google.com/js/plusone.js" lang="es-es"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>

  <script>
  	var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-11469470-3']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    
    $(document).ready(function(){
      $("pre.ruby").snippet("ruby",{style:"vim-dark"});
      $("pre.html").snippet("html",{style:"vim-dark"});
      $("pre.js").snippet("javascript",{style:"vim-dark"});
      $("pre.shell").snippet("sh",{style:"vim-dark"});
    });
  </script>
</head>
<body>
  <div class="container">
    <div class="hero-unit" id="header">
    	<h1><%= link_to "AgileSoft", root_path %></h1>
    </div>

    <div class="navbar">
    	<div class="navbar-inner">
        <ul class="nav">
      		<% if request.fullpath.match /about/ %>
      			<li><%= link_to "Blog", root_path %></li>
            <li class="divider-vertical"></li>
      			<li class="active"><%= link_to "Sobre mi", about_path %></li>
      		<% else %>
      			<li class="active"><%= link_to "Blog", root_path %></li>
            <li class="divider-vertical"></li>
      			<li><%= link_to "Sobre mi", about_path %></li>
      		<% end %>
        </ul>
    	</div>
    </div>

    <div class="row">

      <% if !request.fullpath.match /about/ %>
        <div class="span9">
          <%= yield %>
        </div>
        <div class="span3">
          <div class="right_bar_content">
            <% if @old_posts && !@old_posts.empty? %>
              <h3>Listado de artículos</h3>
              <ul class="nav nav-tabs nav-stacked">
                <% @old_posts.each do |old_post| %>
                  <% if @blog and @blog.id == old_post.id %>
                    <li class="active"><%= link_to old_post.title, "#{posts_path(:post_id => old_post.id)}#post" %></li>
                  <% else %>
                    <li><%= link_to old_post.title, "#{posts_path(:post_id => old_post.id)}#post" %></li>
                  <% end %>
                <% end %>
              </ul>
            <% end %>
          </div>
          <div class="right_bar_content">
            <% if @tags && !@tags.empty? %>
              <h3>Listado de tags</h3>
              <ul class="nav nav-pills nav-stacked">
                <% @tags.each do |tag| %>
                  <li <% if @tag_filter and @tag_filter.index(tag) %>class="active"<% end %>>
                    <%= link_to tag.name.humanize, tags_tag_filter_path, :class => "tag" %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>

          <% if user_signed_in? %>
            <%= render 'partials/admin_panel' %>
          <% end %>

          <div class="right_bar_content">
            <%= link_to image_tag('rss.png'), "/rss.rss" %>
            <%= link_to image_tag('twitter_bird.png'), "https://www.twitter.com/agilesoft_es", :target=>"_blank,", :title => "Síguenos en Twitter" %>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/partials/_admin_panel.html.erb
<div class="right_bar_content">
  <h2>Admin</h2>
  <ul>
    <li><%= link_to 'Nuevo post', create_post_path %></li>
    <li><%= link_to 'Listado de posts', posts_list_path %></li>
    <li><%= link_to 'Salir', destroy_user_session_path, :method => :delete %></li>
  </ul>
</div>

app/views/partials/_botones.html.erb
<% if user_signed_in? %>
	<%= link_to image_tag("bin_big.png"), post_delete_path(:post_id => blog.id), :method => :delete %>
	<%= link_to image_tag("edit.png"), edit_post_path(:post_id => blog.id), :id => "edit_post" %>
<% end %>

<%= link_to image_tag("twitter_bird.png", :size => "48x48"), "https://twitter.com/share?url=http://www.agilesoft.es/posts/#{blog.id}&via=agilesoft_es&text=#{(blog.content[0..100]+"...").gsub(/<\/?[^>]*>/, "")}&lang=es", :target => "_blank" %>
<%= link_to image_tag("facebook.png", :size => "48x48"), "https://facebook.com/sharer.php?u=http://www.agilesoft.es/posts/#{blog.id}", :target => "_blank" %>
<%= link_to image_tag("google_plus.png", :size => "48x48"), "https://plus.google.com/share?url=http://www.agilesoft.es/posts/#{blog.id}", :target => "_blank" %>

app/views/partials/_comentario.html.erb
<div class="comment container" id="comment_<%= comentario.id %>">
	<div class="row">
		<div class="span7">
			<h4><small>Enviado por</small> <span class="big"><%= comentario.author %></span></h4>
		</div>
		<div class="span2 muted">
			<h4><small>el <%= "#{comentario.updated_at.to_s(:mifecha)} a las #{comentario.updated_at.to_s(:mihora)}"%></small></h4>
		</div>
	</div>
	<div class="row">
		<div class="comment_content span9">
			<div class="well well-small">
				<%= sanitize simple_format(comentario.content), :tags => %w(p br strong em u strike) %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="comment_footer span9">
			<% if current_user %>
				<%= link_to image_tag("bin_small.png"), comment_path(:id => comentario.id), :remote => true, :method => :delete %>
			<% end %>
		</div>
	</div>
</div>

app/views/partials/_comentarios.html.erb
<div id="comments" class="container">
	<% if comments && comments.length > 0 %>
		<% if flash[:notice] %>
			<div class="row">
				<div class="span9">
					<div class="alert alert-success">
					  <%= flash[:notice] %>
					</div>
				</div>
			</div>
		<% end %>
		<h3>Comentarios:</h3>
		<% for comment in comments %>
			<div class="row">
				<div class="span9">
					<%= render 'partials/comentario', :comentario => comment %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/partials/_form_comentario.html.erb
<% if flash[:alert] %>
  <div class="row">
    <div class="span9">
      <div class="alert alert-error">
        <%= flash[:alert] %>
      </div>
    </div>
  </div>
<% end %>
<h3>Publicar comentario:</h3>
<%= form_tag comments_path :post_id => @blog.id do |f| %>
  <%= hidden_field_tag 'post_id' %>

  <div class="row">
    <div class="span1">
      <%= label_tag :autor %>
    </div>
    <div class="span8">
      <%= text_field_tag "comment[author]" %>
    </div>
  </div>

  <div class="row">
    <div class="span1">
      <%= label_tag :comentario %>
    </div>
    <div class="span8">
      <%= text_area_tag "comment[content]", nil, :rows => 4 %>
    </div>
  </div>

  <div class="row">
    <div class="span8 offset1">
      <%= submit_tag "Enviar comentario", :class => "btn" %>
    </div>
  </div>
<% end %>

app/views/partials/_form_post.html.erb
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">
  bkLib.onDomLoaded(function(){
    new nicEditor({fullPanel : true}).panelInstance('content');
  });
</script>
            
<%= form_tag save_post_path, :method => :post do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:" %></h2>

      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :post_id, @blog.id %>

  <div class="field">
    <%= label_tag :autor %>
    <br/>
    <%= text_field_tag :author, @blog.author %>
  </div>

  <div class="field">
    <%= label_tag :título %>
    <br/>
    <%= text_field_tag :title, @blog.title %>
  </div>

  <div class="field">
    <%= label_tag :contenido %>
    <br/>
    <%= text_area_tag :content, @blog.content, :rows => 20, :cols => 120 %>
  </div>

  <div class="field">
    <%= label_tag :tags %>
    <%= text_field_tag :tags, @blog.tags.map{|t| t.name.humanize}.join(", ") %>
  </div>

  <div class="field">
    <%= label_tag :updated_at, "Fecha de modificación" %>
    <%= datetime_select :blog, :updated_at %>
  </div>

  <div class="actions">
    <%= submit_tag "Guardar", :class => "btn" %>
  </div>
<% end %>

app/views/partials/_post.html.erb
<div id="post" class="container">
  <div class="row">
    <div class="span6">
      <h3 id="post_title"><%= link_to blog.title, posts_path(post_id: blog.id) %></h3>
    </div>
    <% if !request.fullpath.match /tag_filter/ %>
      <div class="span3 text-right">
        <div id="botones">
          <%= render 'partials/botones', :blog => blog %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="span9">
      <div id="content" class="well">
        <%= raw blog.content %>
      </div>
    </div>
  </div>
  <% if !blog.tags.empty? %>
    <div id="tags" class="row">
      <div class="span9">
        <p>Tags: 
          <% blog.tags.each do |t| %>
            <span class="label label-info"><%= link_to t.name.humanize, tags_tag_filter_path, :class => "tag" %></span>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="span9">
      <p id="firma" class="text-center">Publicado por <span class="big"><%= blog.author %></span> el <%= blog.updated_at.to_s(:mifecha) %> a las <%= blog.updated_at.to_s(:mihora) %>
      </p>
    </div>
  </div>
</div>

app/views/tags/tag_filter.html.erb
<% if @blogs %>
	<% @blogs.each do |blog| %>
		<div id="main_content">
	    <%= render 'partials/post', :blog => blog %>
	  </div>
	<% end %>
<% end %>